export const GET_PAYMENT_REQUEST = 'GET_PAYMENT_REQUEST';
export const GET_PAYMENT_SUCCESS = 'GET_PAYMENT_SUCCESS';
export const GET_PAYMENT_FAILURE = 'GET_PAYMENT_FAILURE';

export const CHARGE_PAYMENT_REQUEST = 'CHARGE_PAYMENT_REQUEST';
export const CHARGE_PAYMENT_SUCCESS = 'CHARGE_PAYMENT_SUCCESS';
export const CHARGE_PAYMENT_FAILURE = 'CHARGE_PAYMENT_FAILURE';
